# HTTP CODE
HTTP_OK = 200

# NetModel
HTTP_CFG_UPLOAD_ERROR = 804
HTTP_CFG_GET_ERROR = 804
HTTP_CFG_NOT_EXIST = 803
HTTP_CFG_DELETED_ERROR = 803

# CheckpointManagement
HTTP_CP_UPLOAD_ERROR = 814
HTTP_CP_GET_ERROR = 814;
HTTP_CP_NOT_EXIST = 803
